FROM ubuntu:18.04

RUN apt-get update && apt-get install -y debootstrap \
qemu-user-static \
u-boot-tools \
unzip \
make \
gcc \
bc \
gcc-7-arm-linux-gnueabihf \
&& rm -rf /var/lib/apt/lists/*

# These packages are necessary for compiling the kernel for the future.
#
#vim \
#sudo \
#gcc \
#bison \
#flex \
#device-tree-compiler \

# These symbolic links are necessary for compiling the kernel for the future.
#RUN ln -s /usr/bin/aarch64-linux-gnu-gcc-8 /usr/local/bin/aarch64-linux-gnu-gcc && \
#ln -s /usr/bin/aarch64-linux-gnu-cpp-8 /usr/local/bin/aarch64-linux-gnu-cpp
